services:

  # flask-server:
  #   build: ./flask-server
  #   container_name: flask-server
  #   restart: always
  #   expose:
  #     - "8000"
  #   volumes:
  #     - ./flask-server:/app
  #   environment:
  #     FLASK_ENV: development
  #     DB_HOST: mariadb
  #     DB_USER: user
  #     DB_PASSWORD: password
  #     DB_NAME: mydb
  #   networks:
  #     - x_network

  midi2mp3:
    build: ./midi2mp3
    container_name: midi2mp3
    restart: always
    volumes:
      - ./midi2mp3:/app                   # sync source code (hot reload)
      - ./midi2mp3/converted:/app/converted        # sync output folder
      - ./midi2mp3/piano.sf2:/app/piano.sf2        # make sure SoundFont is accessible
    environment:
      - FLASK_ENV=development
    command: flask --app app run --host=0.0.0.0 --port=5000 --reload
    expose:
      - "5000"
    networks:
      - x_network

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    expose:
      - "5173"
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    command: ["npm", "run", "dev"]  
    networks:
      - x_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:80"    # for HTTP
      - "8443:443"   # for HTTPS, avoids conflict with host 443
    volumes:
      - ./frontend/dist:/app/dist
      - ./nginx/dev.conf:/etc/nginx/conf.d/dev.conf
      - ./certs/local:/etc/nginx/ssl
    networks:
      - x_network

networks:
  x_network:
    name: x_network 
    driver: bridge
  


