services:

  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app                   # sync source code (hot reload)
      - ./backend/converted:/app/converted        # sync output folder
      - ./backend/piano.sf2:/app/piano.sf2        # make sure SoundFont is accessible
    environment:
      - FLASK_ENV=development
    command: flask --app app run --host=0.0.0.0 --port=5000 --reload --with-threads
    expose:
      - "5000"
    networks:
      - x_network

  frontend:
    build: ./frontend
    container_name: react-frontend
    restart: always
    expose:
      - "5173"
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    command: ["npm", "run", "dev"]  
    networks:
      - x_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"    # for HTTP
      - "443:443"   # for HTTPS, avoids conflict with host 443
    volumes:
      - ./frontend/dist:/app/dist
      - ./nginx/dev.conf:/etc/nginx/conf.d/dev.conf
      - ./certs/local:/etc/nginx/ssl
    networks:
      - x_network

networks:
  x_network:
    name: x_network 
    driver: bridge
  


