services:

  backend:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
      - ./backend/converted:/app/converted
      - ./backend/piano.sf2:/app/piano.sf2
    environment:
      - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:5000 app:app --workers 4 --threads 4
    expose:
      - "5000"
    networks:
      - x_network


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/app/dist
      - ./nginx/prod.conf:/etc/nginx/conf.d/prod.conf
      - ./certs/vps:/etc/nginx/ssl
    networks:
      - x_network

networks:
  x_network:
    name: x_network 
    driver: bridge
  


