services:

  midi2mp3:
    build: ./midi2mp3
    container_name: midi2mp3
    restart: always
    volumes:
      - ./midi2mp3:/app
      - ./midi2mp3/converted:/app/converted
      - ./midi2mp3/piano.sf2:/app/piano.sf2
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    expose:
      - "5000"
    networks:
      - x_network


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/app/dist
      - ./nginx/prod.conf:/etc/nginx/conf.d/prod.conf
      - ./certs/vps:/etc/nginx/ssl
    networks:
      - x_network

networks:
  x_network:
    name: x_network 
    driver: bridge
  


